//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topevery.FMP.ObjectModel {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topevery.FMP.ObjectModel.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在ID为:{0}的文件，不能创建对应的文件。 的本地化字符串。
        /// </summary>
        internal static string ExsitsFileID {
            get {
                return ResourceManager.GetString("ExsitsFileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取数据出错，出错原因为：{0}。 的本地化字符串。
        /// </summary>
        internal static string FetchExecuteResultError {
            get {
                return ResourceManager.GetString("FetchExecuteResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取出 的本地化字符串。
        /// </summary>
        internal static string FetchExecuteResultNoData {
            get {
                return ResourceManager.GetString("FetchExecuteResultNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已关闭。 的本地化字符串。
        /// </summary>
        internal static string FileIsClosed {
            get {
                return ResourceManager.GetString("FileIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID为:{0}的文件为只读，不能更新对应的文件。 的本地化字符串。
        /// </summary>
        internal static string FileReadOnly {
            get {
                return ResourceManager.GetString("FileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的文件ID。 的本地化字符串。
        /// </summary>
        internal static string InvalidateFileID {
            get {
                return ResourceManager.GetString("InvalidateFileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的文件操作模式（文件操作模式不能为FileMode.None)。 的本地化字符串。
        /// </summary>
        internal static string InvalidateFileMode {
            get {
                return ResourceManager.GetString("InvalidateFileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在ID为:{0}的文件，不能打开对应的文件。 的本地化字符串。
        /// </summary>
        internal static string NotExsitsFileID {
            get {
                return ResourceManager.GetString("NotExsitsFileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行的结果返回空值 的本地化字符串。
        /// </summary>
        internal static string NullReturnValue {
            get {
                return ResourceManager.GetString("NullReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象已经设置为只读，属性：{0} 不能修改。 的本地化字符串。
        /// </summary>
        internal static string PropertyReadonlyError {
            get {
                return ResourceManager.GetString("PropertyReadonlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已经设置了查询所有的记录，不能对OperationItemsID进行操作. 的本地化字符串。
        /// </summary>
        internal static string SetRetriveItemAfterHaveSettedAllOperationRecordError {
            get {
                return ResourceManager.GetString("SetRetriveItemAfterHaveSettedAllOperationRecordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新数据出错，出错原因为：{0}。 的本地化字符串。
        /// </summary>
        internal static string UpdateExecuteResultError {
            get {
                return ResourceManager.GetString("UpdateExecuteResultError", resourceCulture);
            }
        }
    }
}
